[package]
name = "dasher"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "dasher"
path = "src/main.rs"

[dependencies]
santa-lang = { path = "../lang" }
clap.workspace = true
atty.workspace = true

[dev-dependencies]
expect-test.workspace = true
